multilib_header.bbclass: downgrade missing header from error to warning
Older versions of the kernel may not provide all the expected libc
headers. For example, linux 3.12.74 libc headers generate the
following error with OE 3.0:

  ERROR: linux-libc-headers-3.12.74-r0 do_install: oe_multilib_header: Unable to find header asm/perf_regs.h.
  ERROR: linux-libc-headers-3.12.74-r0 do_install: oe_multilib_header: Unable to find header asm/bpf_perf_event.h.

Downgrade the missing headers from an error to a warning to avoid
causing an unnecessary build failure.

Signed-off-by: Andre McCurdy <armccurdy@gmail.com>