dhcp: fix a NSUPDATE compiling issue
This patch fixes a following issue:
| omapip/isclib.c: In function 'dns_client_init':
| omapip/isclib.c:356:18: error: 'dhcp_context_t {aka struct dhcp_context}' has no member named 'dnsclient'
|   if (dhcp_gbl_ctx.dnsclient == NULL) {
|                   ^
| omapip/isclib.c:363:24: error: 'dhcp_context_t {aka struct dhcp_context}' has no member named 'dnsclient'
|            &dhcp_gbl_ctx.dnsclient,
|                         ^
| omapip/isclib.c:364:24: error: 'dhcp_context_t {aka struct dhcp_context}' has no member named 'use_local4'
|            (dhcp_gbl_ctx.use_local4 ?
|                         ^
| omapip/isclib.c:365:25: error: 'dhcp_context_t {aka struct dhcp_context}' has no member named 'local4_sockaddr'
|             &dhcp_gbl_ctx.local4_sockaddr
|                          ^
| omapip/isclib.c:367:24: error: 'dhcp_context_t {aka struct dhcp_context}' has no member named 'use_local6'
|            (dhcp_gbl_ctx.use_local6 ?
|                         ^
| omapip/isclib.c:368:25: error: 'dhcp_context_t {aka struct dhcp_context}' has no member named 'local6_sockaddr'
|             &dhcp_gbl_ctx.local6_sockaddr

Signed-off-by: Ming Liu <liu.ming50@gmail.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>
(cherry picked from commit e36076b6feca481b7a7a44b1c03c4cfca2dd8c48)