libcap: Add gperf-native to depends
Fixes
|  gperf_case_strncmp (register const char *s1, register const char *s2, register size_t n)
|                                                                                 ^~~~~~
| ./_caps_output.gperf:96:53: error: unknown type name 'size_t'
|  __cap_hash_name (register const char *str, register size_t len)
|                                                      ^~~~~~
| ./_caps_output.gperf:200:55: error: unknown type name 'size_t'
|  __cap_lookup_name (register const char *str, register size_t len)
|                                                        ^~~~~~
| ./_caps_output.gperf:200:1: error: conflicting types for '__cap_lookup_name'
|  __cap_lookup_name (register const char *str, register size_t len)
|  ^~~~~~~~~~~~~~~~~
| ./_caps_output.gperf:33:29: note: previous declaration of '__cap_lookup_name' was here
|  const struct __cap_token_s *__cap_lookup_name(const char *, unsigned int);
|                              ^~~~~~~~~~~~~~~~~
| cap_text.c: In function 'cap_to_name':
| cap_text.c:291:2: warning: ignoring return value of 'asprintf', declared with attribute warn_unused_result [-Wunused-result]
|   asprintf(&tmp, "%u", cap);
|   ^~~~~~~~~~~~~~~~~~~~~~~~~
| make[1]: *** [Makefile:63: cap_text.o] Error 1

Signed-off-by: Khem Raj <raj.khem@gmail.com>
Signed-off-by: Ross Burton <ross.burton@intel.com>
(cherry picked from commit 092954cf2fba5020443f09c8e1fbc1788f704f10)