lighttpd: remove fam as a PACKAGECONFIG option
lighttpd builds fail if "fam" (and therefore gamin) is enabled.

In conf/local.conf:

    CORE_IMAGE_EXTRA_INSTALL += "lighttpd"
    PACKAGECONFIG_append_pn-lighttpd = " fam"

bitbake error:

    ERROR: Nothing PROVIDES 'gamin' (but /yow-lpggp31/tgamblin/oe-core.git/meta/recipes-extended/lighttpd/lighttpd_1.4.54.bb DEPENDS on or otherwise requires it)
    NOTE: Runtime target 'lighttpd' is unbuildable, removing...
    Missing or unbuildable dependency chain was: ['lighttpd', 'gamin']
    ERROR: Required build target 'core-image-minimal' has no buildable providers.
    Missing or unbuildable dependency chain was: ['core-image-minimal', 'lighttpd', 'gamin']

Since gamin hasn't been maintained for several years, this should
be removed from the list of lighttpd PACKAGECONFIG options.
--without-fam is hard-coded in EXTRA_OECONF for good measure.

Signed-off-by: Trevor Gamblin <trevor.gamblin@windriver.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>
(cherry picked from commit ea714fff3869ef19cf1dc94bdffbca2c69658954)